### ISSUE TITLE
Summary is not helpful

### ISSUE THREAD

**Issue by razzeee** [flathub/dev.hdos.HDOS#2]
Please make a more helpful summary https://github.com/flathub/dev.hdos.HDOS/blob/master/dev.hdos.HDOS.appdata.xml#L6

It's pretty useless, if I don't know what `HDOS` or `OSRS` are

**Comment by supermxn** [comment]
#3 went ahead and pushed a pr

**Comment by Brainfree** [comment]
Merged, thanks
